{% set name = "beautifulsoup4" %}
{% set version = "4.13.5" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e70131382930e7c3de33450a2f54a63d5e4b19386eab43a5b34d594268f3695

build:
  number: 0
  skip: true  # [py<37]

outputs:
  - name: {{ name }}
    script: build_base.bat  # [win]
    script: build_base.sh   # [unix]
    requirements:
      host:
        - pip
        - python
        - hatchling
      run:
        - python
        - soupsieve >1.2
        - typing-extensions >=4.0.0
    test:
      source_files:
        - bs4/tests
      imports:
        - bs4
        - bs4.builder
      requires:
        - pip
        - lxml
        - html5lib
        - pytest >=6
      commands:
        - pip check
        - mkdir ${SP_DIR}/bs4/tests  # [unix]
        - cp -r bs4/tests ${SP_DIR}/bs4/  # [unix]
        - md "%SP_DIR%\bs4\tests"  # [win]
        - xcopy /E /I /Y "bs4\tests" "%SP_DIR%\bs4\tests"  # [win]
        - pytest --pyargs bs4.tests

  - name: bs4
    build:
      noarch: generic
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('beautifulsoup4', max_pin="x.x.x") }}
    test:
      imports:
        - bs4
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://www.crummy.com/software/BeautifulSoup/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library designed for screen-scraping
  description: |
    Beautiful Soup is a library for pulling data out of HTML and XML files.
    It provides ways of navigating, searching, and modifying parse trees.
  doc_url: https://beautiful-soup-4.readthedocs.io/
  dev_url: https://code.launchpad.net/beautifulsoup

extra:
  recipe-maintainers:
    - jschueller
    - nehaljwani
  skip-lints:
    - missing_wheel
    - missing_python_build_tool
