{% set version = "4.6.1" %}
{% set name = "beautifulsoup4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd43a3b26d2886acd63070c43da821b60dea603eb6d45bab0294aac6129adbfa

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - bs4

about:
  home: http://www.crummy.com/software/BeautifulSoup/
  license: MIT
  license_family: MIT
  license_file: COPYING.txt
  summary: Python library designed for screen-scraping
  description: |
    Beautiful Soup is a library for pulling data out of HTML and XML files.
    It provides ways of navigating, searching, and modifying parse trees.
  doc_url: http://beautiful-soup-4.readthedocs.io/en/latest/
  doc_source_url: https://github.com/newvem/beautifulsoup4/blob/master/doc/source/index.rst
  dev_url: https://code.launchpad.net/beautifulsoup

extra:
  recipe-maintainers:
    - jschueller
    - nehaljwani
