{% set name = "beautifulsoup4" %}
{% set version = "4.15.0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 288e3ca7d54b06f2ac191970bc275c1939cb46d450b255bf6718b04aa37ab4f7

build:
  number: 0
  skip: true  # [py<37]

outputs:
  - name: {{ name }}
    script: build_base.bat  # [win]
    script: build_base.sh  # [unix]
    requirements:
      host:
        - pip
        - python
        - hatchling
      run:
        - python
        - soupsieve >=1.6.1
        - typing-extensions >=4.0.0

# E Failed: DID NOT RAISE <class 'bs4.exceptions.ParserRejectedMarkup'>
# https://bugzilla.redhat.com/show_bug.cgi?id=2368745
{% set deselect_tests = " --deselect=test_fuzz.py::TestFuzz::test_rejected_markup" %}
{% set deselect_tests = deselect_tests + " --deselect=test_htmlparser.py::TestHTMLParserTreeBuilder::test_rejected_input" %}
# https://bugs.launchpad.net/beautifulsoup/+bug/2134346
{% set deselect_tests = deselect_tests + " --deselect=test_lxml.py::TestLXMLTreeBuilder::test_surrogate_in_character_reference" %}
# E           ValueError: invalid literal for int() with base 10: '2fontipt><!--</script><scri�pt><������������pt><script<>!--</script6<�<head/�Xpe" 
  # charse/�\x00ript><s��cript><!-pt><script<>!--</script6<�<head/�Xpe" charse/�\x00ript><s��cript><!--</scrixt><s�<!--</
# https://bugs.launchpad.net/beautifulsoup/+bug/2134393
{% set deselect_tests = deselect_tests + " --deselect=test_fuzz.py::TestFuzz::test_deeply_nested_document_without_css" %}

    test:
      source_files:
        - bs4/tests
      imports:
        - bs4
        - bs4.builder
      requires:
        - pip
        - lxml
        - html5lib
        - pytest >=6
      commands:
        - pip check
        - mkdir ${SP_DIR}/bs4/tests  # [unix]
        - cp -r bs4/tests ${SP_DIR}/bs4/  # [unix]
        - md "%SP_DIR%\bs4\tests"  # [win]
        - xcopy /E /I /Y "bs4\tests" "%SP_DIR%\bs4\tests"  # [win]
        - pytest --pyargs bs4.tests {{ deselect_tests }}
  - name: bs4
    build:
      noarch: generic
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('beautifulsoup4', max_pin="x.x.x") }}
    test:
      imports:
        - bs4
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://www.crummy.com/software/BeautifulSoup
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library designed for screen-scraping
  description: |
    Beautiful Soup is a library for pulling data out of HTML and XML files.
    It provides ways of navigating, searching, and modifying parse trees.
  doc_url: https://beautiful-soup-4.readthedocs.io
  dev_url: https://code.launchpad.net/beautifulsoup

extra:
  recipe-maintainers:
    - jschueller
    - nehaljwani
  skip-lints:
    - missing_wheel
    - missing_python_build_tool
