{% set version = "4.8.1" %}

package:
  name: beautifulsoup4
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/beautifulsoup4/beautifulsoup4-{{ version }}.tar.gz
  sha256: 6135db2ba678168c07950f9a16c4031822c6f4aec75a65e0a97bc5ca09789931

build:
  # Uses 2to3 and cannot be noarch.
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - soupsieve >=1.2

test:
  imports:
    - bs4

about:
  home: http://www.crummy.com/software/BeautifulSoup/
  license: MIT
  license_family: MIT
  license_file: COPYING.txt
  summary: Python library designed for screen-scraping
  description: |
    Beautiful Soup is a library for pulling data out of HTML and XML files.
    It provides ways of navigating, searching, and modifying parse trees.
  doc_url: http://beautiful-soup-4.readthedocs.io/en/latest/
  doc_source_url: https://github.com/newvem/beautifulsoup4/blob/master/doc/source/index.rst
  dev_url: https://code.launchpad.net/beautifulsoup

extra:
  recipe-maintainers:
    - jschueller
    - nehaljwani
