{% set version = "4.12.0" %}

package:
  name: beautifulsoup4-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/beautifulsoup4/beautifulsoup4-{{ version }}.tar.gz
  sha256: c5fceeaec29d09c84970e47c65f2f0efe57872f7cff494c9691a26ec0ff13234

build:
  number: 0
  skip: True  # [py<36]

outputs:
  - name: beautifulsoup4
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - soupsieve >=1.2
      run_constrained:
        - html5lib
        - lxml
      test:
        imports:
          - bs4
          - bs4.builder
        requires:
          - pip
        commands:
          - pip check

  - name: bs4
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('beautifulsoup4', max_pin="x.x.x") }}
    test:
      imports:
        - bs4

about:
  home: https://www.crummy.com/software/BeautifulSoup/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library designed for screen-scraping
  description: |
    Beautiful Soup is a library for pulling data out of HTML and XML files.
    It provides ways of navigating, searching, and modifying parse trees.
  doc_url: https://beautiful-soup-4.readthedocs.io/en/latest/
  dev_url: https://code.launchpad.net/beautifulsoup

extra:
  recipe-maintainers:
    - jschueller
    - nehaljwani
