travis:
  secure:
    BINSTAR_TOKEN: r1wc8j/ShA0J9cepaGi9dgvaf/tC9hs0Eb1KvGogFIitEliZxRqcMsZ2PR5dJYK9rOuYX6ctH5P9QllajB2coq06v9QNWJ30dS6fVjdrQkDF7tbg52kyXvVRJyHqpsqyWCvwsP2sFvJgQzBfFZazlQN9DoC6RogoYrhsnCLm2D7btOGqJ8wSouR1q8ADBjTJsKres8i6yWZc6G8zjjKZlJb0ik3KS/ZHjR+6LQEaPcjI7tuWk7acU2FhCYpWgC2BlgLghsq2j37WUNCZdI1C4w15eBI/5dNrZyKau1qN3pX50/cqAmuNcWDaxA19/afe+xTVBUX/RJcUyo1I1VWe9WeJ46ZaEZYYoL3ZGmZMwRwt9iw1yu+pN43Cli8tdOmX3HQHmRD3vyNW5JaLZpwKDIFrS4rzSBx/zJCWQx6FGji9CfVMYnU2Qn8GqpNtO2kqagT/QjfJ3TsSHOOsBtXoBujxkv2T8Inx58OfY2NL8FqIVGR1R5LHC6JkTW415BGtS1XAB8FtIdt67PGidFYHTBLr8urwdM8Xb7MB8fJnoghnD3YbFzz2BCidqJrtuSDeion36Gcu1D7WdcXfO2rIOQOxemIhSQNmTcuG6HeasXXL2PvRsPaq6lFByWD00xp2URfaLSa4cjazmNo0HGgRaNAjR1wUGxso3w1pB7Y2Gb0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
