travis:
  secure:
    BINSTAR_TOKEN: u3sJxNSx/eD1S/HMlYm/ClLjsve0tQnEWqDDaM8gPPSxAseyD90Kiq8TgrpygdEqYLdZvN9Uzj9vyZKMLbP/utXd95KjjRkIJtO189KAC9W5AFjacEj1nnIevYYOL6sDVIfEO/KP7sydIxDQ/cWQCDBDBRnzqP0RDC5eMo8Gn43gR6R4G75icqg5zGy+v45mpJ/Q1MlQJrSw7+HyOt+Ug3/D6pjzNLIcf/RWPjHOEmoBY7BK3b2imGVVNXLi1x7TJotGOu6/rZ3BPK6vTO4Me5kU/bWAwJz3NlZM1skziaVMOb9pBaWVTKkS7eGR+pLayCnZiUJEmx4GXZOCoFsO+v+G19dyqaP+YfVfjKFqn59uZ68lYShv5B0K4KSSaZSOHjZSfapvceTPFKuGwYJtPB2F7b3ypyKmlunJ69/jZK2aYmnA7NmMxtdo+n+Pxi9/b/grVccKtWyBJF9lIpueJ+lkEltprc/HjFmeNT5Q1TvLXTvpXIixvU1VGIpDN4/VqyA2dLY+HSemzp///Fh4VOdWd4qNjic5LEHv8Uc+qhf31Q3wwVICcl2S4zNuhl17nWAvRzEYUibMAc0Pm6uCnMpjq1HHiaIX51di6TDdwbTl+kpapnmNyshTVASZ14nD1XmFN5FFNpFckwNFHvLLaeAQxzNlThTA9P7oVzE8UFA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
